version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3-angular-bucket-test}}"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - ng help
        - echo Build started 
        - ng build --${BUILD_ENV}
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
