version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3-angular-bucket-test}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - cd maad-cars/
        - ng build --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'maad-cars/dist*'
    discard-paths: yes
