version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "s3-angular-bucket-test"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - ng build --prod
  post_build:
     commands:
        - aws s3 cp ${BUILD_FOLDER} s3:${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
        - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
