version: 0.2
env:
    variables:
        S3_BUCKET: "{{s3-angular-bucket-test}}"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - ng build --prod --aot
      post_build:
         commands:
            - aws s3 cp dist s3:${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
